### ISSUE TITLE
Missing feature: ZCL_EXCEL_READER_2007 not able to load the table styles from Excel file

### ISSUE THREAD

**Issue by hamida-ashna** [abap2xlsx/abap2xlsx#1168]
I tried to write data to an existing Excel file. But after writing data, I saw that all table styles are removed from that file. And finally I found the reason of it. After reading the file using zcl_excel_reader_2007, I found it that the reader is not able to read style of tables in a sheet (reader can read other styles but can't load table style). 

<img width="619" alt="2229243-screenshot-2023-11-28-173845" src="https://github.com/abap2xlsx/abap2xlsx/assets/75003524/c38260c3-ce9b-4684-9afb-dd93f245115a">
<img width="631" alt="2229244-screenshot-2023-11-29-144716" src="https://github.com/abap2xlsx/abap2xlsx/assets/75003524/26793ee0-ccd1-45c2-a415-a8930804684b">

In here I attach the file which I used for my work. And like zdemo_excel22.prog.abap, simply I followed the below steps:
1- Read the existing Excel file using ZCL_EXCEL_READER_2007 
2- get the active worksheet
3- bind the table
4- Write data

[C_AUFNR_KSTAR_COPY.xlsx](https://github.com/abap2xlsx/abap2xlsx/files/13760132/C_AUFNR_KSTAR_COPY.xlsx)

**Comment by sandraros** [comment]
Thank you for posting the issue. It's a missing feature.
Instead of using the demo program "22", the missing feature can be seen directly by running the program [`zdemo_excel37`](https://github.com/abap2xlsx/demos/blob/main/src/zdemo_excel37.prog.abap).

The first issue is about reading the tables. I posted an issue a few weeks ago (#1158). The proposed fix will partly solve the issue you indicate because a default table has colored headings, but not exactly the original colors.

Let me check and propose a fix.

**Comment by sandraros** [comment]
Could you import the pull request #1159 and test please? If it's okay for you, I will merge the fix.

**Comment by hamida-ashna** [comment]
@sandraros, 
Thank you so much, I checked the #1159 issue (the active sheet contains 0 tables) and yeah both issues are related to each other so, you can merge the fix.
