### ISSUE TITLE
Range with a name and only sheet visibility gets lost while reading 08_Range.xlsx

### ISSUE THREAD

**Issue by darnoc312** [abap2xlsx/abap2xlsx#1233]
Hello,

I found a very small bug in reader's method load_workbook.
The output of ZDEMO_EXCEL8 cannot be reread by ZDEMO_EXCEL37 completly.
The range with the name 'A_range_with_sheet_visibility' is no more exsisting in '37_passthrough.xlsx'.

**Comment by sandraros** [comment]
Excel file by `ZDEMO_EXCEL8` ([08_Range.xlsx](https://github.com/user-attachments/files/15751152/08_Range.xlsx)):

![image](https://github.com/abap2xlsx/abap2xlsx/assets/34005250/2d715e47-57c5-4850-89c8-616b0811b5da)

Excel file by `ZDEMO_EXCEL37` ([08_Range_after_read_write_by_37.xlsx](https://github.com/user-attachments/files/15751153/08_Range_after_read_write_by_37.xlsx)):

![image](https://github.com/abap2xlsx/abap2xlsx/assets/34005250/d877c2af-2f21-4553-9d60-b4e1076b4d2c)

Note that the other range name has been kept successfully:

![image](https://github.com/abap2xlsx/abap2xlsx/assets/34005250/8f4cbd99-8d47-40f5-b296-26cc4d48963b)

It's because the issue is only about the names with sheet visibility, not workbook visibility ("scope"):

![image](https://github.com/abap2xlsx/abap2xlsx/assets/34005250/69596b54-1536-446e-b9d1-f924e5587499)

![image](https://github.com/abap2xlsx/abap2xlsx/assets/34005250/1ca23f2f-aa1d-4951-b693-32bbf40c6c24)
