### ISSUE TITLE
Worksheet's method set_title doesn't handle escaped titles and sheetlocal ranges 

### ISSUE THREAD

**Issue by darnoc312** [abap2xlsx/abap2xlsx#1235]
Hello,

please try the following demo program similar to ZDEMO_EXCEL8 which sets title at the end again

```abap
REPORT zdemo_excel8_test.

DATA: lo_excel                TYPE REF TO zcl_excel,
      lo_worksheet            TYPE REF TO zcl_excel_worksheet,
      lo_range                TYPE REF TO zcl_excel_range.

DATA: lv_title          TYPE zexcel_sheet_title.

CONSTANTS: gc_save_file_name TYPE string VALUE '08_Range.xlsx'.
INCLUDE zdemo_excel_outputopt_incl.


START-OF-SELECTION.

  CREATE OBJECT lo_excel.

  " Get active sheet
  lo_worksheet = lo_excel->get_active_worksheet( ).
  lv_title = 'Escaped title text'.                                        "Title for testing
  lo_worksheet->set_title( lv_title ).
  lo_range = lo_excel->add_new_range( ).
  lo_range->name = 'range'.
  lo_range->set_value( ip_sheet_name    = lv_title
                       ip_start_column  = 'C'
                       ip_start_row     = 4
                       ip_stop_column   = 'C'
                       ip_stop_row      = 8 ).


  lo_worksheet->set_cell( ip_row = 4 ip_column = 'C' ip_value = 'Apple' ).
  lo_worksheet->set_cell( ip_row = 5 ip_column = 'C' ip_value = 'Banana' ).
  lo_worksheet->set_cell( ip_row = 6 ip_column = 'C' ip_value = 'Blueberry' ).
  lo_worksheet->set_cell( ip_row = 7 ip_column = 'C' ip_value = 'Ananas' ).
  lo_worksheet->set_cell( ip_row = 8 ip_column = 'C' ip_value = 'Grapes' ).

  " Define another Range with a name longer than 40 characters that
  " tests the fix of issue #168 ranges namescan be only up to 20 chars

  lo_range = lo_excel->add_new_range( ).
  lo_range->name = 'A_range_with_a_name_that_is_longer_than_20_characters'.
  lo_range->set_value( ip_sheet_name    = lv_title
                       ip_start_column  = 'D'
                       ip_start_row     = 4
                       ip_stop_column   = 'D'
                       ip_stop_row      = 5 ).
  lo_worksheet->set_cell( ip_row = 4 ip_column = 'D' ip_value = 'Range Value 1' ).
  lo_worksheet->set_cell( ip_row = 5 ip_column = 'D' ip_value = 'Range Value 2' ).

  " issue #163
  " Define another Range with sheet visibility
  lo_range = lo_worksheet->add_new_range( ).
  lo_range->name = 'A_range_with_sheet_visibility'.
  lo_range->set_value( ip_sheet_name    = lv_title
                       ip_start_column  = 'E'
                       ip_start_row     = 4
                       ip_stop_column   = 'E'
                       ip_stop_row      = 5 ).
  lo_worksheet->set_cell( ip_row = 4 ip_column = 'E' ip_value = 'Range Value 3' ).
  lo_worksheet->set_cell( ip_row = 5 ip_column = 'E' ip_value = 'Range Value 4' ).
  " issue #163

  lo_worksheet->set_title( ip_title = 'Sheet1' ).                          "And now rename them all

*** Create output
  lcl_output=>output( lo_excel ).
```

Currently nothing is renamed and the names manager looks like this:
![image](https://github.com/abap2xlsx/abap2xlsx/assets/135710507/95a59396-2de2-49d0-8480-f0b7e9fccdfd)
All values are empty.

After the fix there are values again:
![image](https://github.com/abap2xlsx/abap2xlsx/assets/135710507/0a2fef14-ed13-4a75-a0a4-76ffa2402cdc)

**Comment by sandraros** [comment]
So, the bug is that the "sheetlocal" named ranges do not reflect the new name of a sheet. It's demonstrated by the program at the end of this comment, there are two test cases defined to test the fix:
1. The sheet "Bug 1" contains a sheet-scope range named "A_range_with_sheet_visibility" referring to the cell `'Bug 1'!$E$4:$E$4`), then the sheet is renamed "Bug1". Expected result: the sheetlocal named range should become `Bug1!$E$4:$E$4`.
2. The sheet "Bug2" contains a sheet-scope range named "A_range_with_sheet_visibility" referring to the cell (`Bug2!$E$4:$E$4`), then the sheet is renamed "Bug 2". Expected result: the sheetlocal named range should become `'Bug 2'!$E$4:$E$4`.

Actual result of the program below (before abap2xlsx fix): [bug_1235_set_title_and_sheet_range_actual.xlsx](https://github.com/user-attachments/files/15751602/bug_1235_set_title_and_sheet_range_actual.xlsx)
- "E4" is shown instead of "A_range_with_sheet_visibility":
  ![image](https://github.com/abap2xlsx/abap2xlsx/assets/34005250/c5b6eb84-6d21-47ff-800e-8e6c31bcf949)
  ![image](https://github.com/abap2xlsx/abap2xlsx/assets/34005250/d6e9a290-0645-4c75-8b2b-c644750a50b3)
- In the Name manager, the named ranges refer to incorrect sheet names ("Bug 1" and "Bug2" don't exist):
  ![image](https://github.com/abap2xlsx/abap2xlsx/assets/34005250/55ec2fbb-d7ca-44c9-a6e5-55ee0e817d0b)
- Internally, `workbook.xml` of the XLSX file contains these invalid sheet names:
  ![image](https://github.com/abap2xlsx/abap2xlsx/assets/34005250/8bfdb82c-804b-4a09-af7b-472f7876385c)

Expected result: [bug_1235_set_title_and_sheet_range_expected.xlsx](https://github.com/user-attachments/files/15751603/bug_1235_set_title_and_sheet_range_expected.xlsx)
- In both sheets, the named range now refers correctly to the cell:
  ![image](https://github.com/abap2xlsx/abap2xlsx/assets/34005250/76c0c0fd-c15a-4544-97cf-ad78d2716ddd)
- Name manager:
  ![image](https://github.com/abap2xlsx/abap2xlsx/assets/34005250/a11febe5-cc04-452f-b292-21bf7312a821)
- File `workbook.xml`:
  ![image](https://github.com/abap2xlsx/abap2xlsx/assets/34005250/f1cc1556-c976-4900-afd0-784e312ca3bc)

Minimal reproducible example:
```abap
REPORT.
DATA lo_excel       TYPE REF TO zcl_excel.
DATA lo_worksheet   TYPE REF TO zcl_excel_worksheet.
DATA lo_range       TYPE REF TO zcl_excel_range.
DATA lv_sheet_title TYPE zexcel_sheet_title.
CONSTANTS gc_save_file_name TYPE string VALUE 'bug_1235_set_title_and_sheet_range.xlsx'.
INCLUDE zdemo_excel_outputopt_incl.
START-OF-SELECTION.
  lo_excel = NEW #( ).

  " BUG 1
  lo_worksheet = lo_excel->get_active_worksheet( ).
  lv_sheet_title = 'Bug 1'.
  lo_worksheet->set_title( lv_sheet_title ).
  lo_range = lo_worksheet->add_new_range( ).
  lo_range->name = 'A_range_with_sheet_visibility'.
  lo_range->set_value( ip_sheet_name   = lv_sheet_title
                       ip_start_column = 'E'
                       ip_start_row    = 4
                       ip_stop_column  = 'E'
                       ip_stop_row     = 4 ).
  lo_worksheet->set_cell( ip_row    = 4
                          ip_column = 'E'
                          ip_value  = 'Range value' ).
  lo_worksheet->set_title( ip_title = 'Bug1' ).

  " BUG 2
  lv_sheet_title = 'Bug2'.
  lo_worksheet = lo_excel->add_new_worksheet( lv_sheet_title ).
  lo_range = lo_worksheet->add_new_range( ).
  lo_range->name = 'A_range_with_sheet_visibility'.
  lo_range->set_value( ip_sheet_name   = lv_sheet_title
                       ip_start_column = 'E'
                       ip_start_row    = 4
                       ip_stop_column  = 'E'
                       ip_stop_row     = 4 ).
  lo_worksheet->set_cell( ip_row    = 4
                          ip_column = 'E'
                          ip_value  = 'Range value' ).
  lo_worksheet->set_title( ip_title = 'Bug 2' ).

  lcl_output=>output( lo_excel ).
```
