### ISSUE TITLE
Yet another autofilter problem using converter and ALV

### ISSUE THREAD

**Issue by darnoc312** [abap2xlsx/abap2xlsx#1238]
Use ZDEMO_EXCEL32 and select one column filter with one value to avoid side effect with the other autofilter issue.
In my example i chosed '00000111' for AGENCYNUM. You get the following result:

[32_Export_Convert #1.xlsx](https://github.com/user-attachments/files/15834749/32_Export_Convert.1.xlsx)

XML Autofilter's ref in xl/worksheets/sheet1.xml is wrongly T1:T1 and nothing is hidden.
Converter's method set_autofilter_area sets row_start to 1. row_end remains 0.
Currently autofilter's method validate_area then exchanges these values wrongly. row_start = 0, row_end = 1.
Then the following validation code sets row_start because of 0 to 1. Final result: row_start = 1 and row_end = 1.

The bug is the change of autofilters method validate_area with PR #822. The change there is useful but why the changed code has been moved ?
It seems to be obvious, that the behaviour of row and column should be similar in this method. But since this PR that has no longer been the case.

So the first fix is moving this code to its previous place.
Then you get the following result:

[32_Export_Convert #2.xlsx](https://github.com/user-attachments/files/15834752/32_Export_Convert.2.xlsx)

XML Autofilter's ref is T1:T52 and the header is wrongly hidden.
Converter's method set_autofilter_area sets row_start to 1. row_end remains 0.
Then autofilter's method validate_area sets row_end because of 0 to highest_row correctly and no further exchange will happen.
Final result: row_start = 1 and row_end = 52.

The next bug is the setting of row_start in converter's method set_autofilter_area to 1 instead to the value of converter's field w_row_int (The converter call in ZDEMO_EXCEL32 starts at row 2 and column 2).
After this is also fixed you get the following result:

[32_Export_Convert #3.xlsx](https://github.com/user-attachments/files/15834756/32_Export_Convert.3.xlsx)

XML Autofilter's ref is now correctly T2:T52.
Converter's method set_autofilter_area sets row_start to 2 (the value of w_row_int). row_end remains 0.
Then autofilter's method validate_area sets row_end because of 0 to highest_row correctly and no further exchange will happen.
Final result: row_start = 2 and row_end = 52.

**Comment by sandraros** [comment]
To make it clear, the issue is "ALV converter downloads Excel file without the ALV filter", and here are the reproduce steps (the rest of your post is the analysis that I would prefer to have in the next comments or in the Pull Request).

Run ZDEMO_EXCEL32  

Select the Agency column and click Filter as shown here:

![image](https://github.com/abap2xlsx/abap2xlsx/assets/34005250/95c2a44b-29b0-452a-a297-9b2bed8558e8)

Type the agency number 111, and Validate as shown here:

![image](https://github.com/abap2xlsx/abap2xlsx/assets/34005250/9f5fb9c6-4636-4b9a-8c1f-4dc9f13377ce)  

One can see that the bookings from the agency number 111 are displayed, as shown here:

![image](https://github.com/abap2xlsx/abap2xlsx/assets/34005250/588cb2b7-3a88-4933-8416-22be8cd96980)

Click on the button "Excel converter", select a folder where to generate the Excel file:

![image](https://github.com/abap2xlsx/abap2xlsx/assets/34005250/20de44aa-4da6-4ec1-a4b7-8c7e8109941f)

<img src="https://github.com/abap2xlsx/abap2xlsx/assets/34005250/74b4480e-72ea-46bd-b587-9096ea7766e4" width="200px"/>

![image](https://github.com/abap2xlsx/abap2xlsx/assets/34005250/96ba9c9b-a28b-4811-82ff-50e9dac26046")

Open the generated Excel file 32_Export_Convert.xlsx, one can see that the Agency column is missing the filter:

![image](https://github.com/abap2xlsx/abap2xlsx/assets/34005250/21ce6bf4-dad4-4ce0-89a5-d91010d055f2)

Expected result:

![image](https://github.com/user-attachments/assets/db99a814-ab34-4816-81ce-c853b3e8c6a1)

**Comment by darnoc312** [comment]
This also might be the reason for the "weird filter area" from #1017 which "does not take effect".

**Comment by bigld** [comment]
There is coding in report ZDEMO_EXCEL33 to set converter options ( lo_converter->set_option( ls_option ).) 
So if ZDEMO_EXCEL33 was executed once filters (and other stuff)  are no longer used by the excel converter => eg ZDEMO_EXCEL32 ignores ALV filter

This report can be used to delete the stored options and ZDEMO_EXCEL32 works with PR #1239 

```
REPORT zexcel_del_converter_options.

START-OF-SELECTION.

  DATA: srtfd TYPE indx_srtfd.
  CONCATENATE 'EXCEL_' sy-uname INTO srtfd.
  DELETE FROM DATABASE indx(xl) ID srtfd.
```

**Comment by sandraros** [comment]
Thanks. `ZDEMO_EXCEL32` fixed to set the options.
