### ISSUE TITLE
change_cell_style( ) clears the cell's style object

### ISSUE THREAD

**Issue by edward-pelyavskyy** [abap2xlsx/abap2xlsx#294]
After calling lo_worksheet->change_cell_style( ), lo_worksheet->get_cell( ) returns an initial (not bound) ep_style. Run the program below and see how the second PERFORM check_style shows "B2 HAS NO STYLE".

REPORT  zevptest01.

DATA: lo_excel                TYPE REF TO zcl_excel,
      lo_worksheet            TYPE REF TO zcl_excel_worksheet,
      lo_hyperlink            TYPE REF TO zcl_excel_hyperlink,
      column_dimension        TYPE REF TO zcl_excel_worksheet_columndime.

DATA lo_style_color         TYPE REF TO zcl_excel_style.
DATA lv_style_color_guid    TYPE zexcel_cell_style.

DATA ls_border TYPE zexcel_s_cstyle_border.
DATA ls_border_x TYPE zexcel_s_cstylex_border.

CONSTANTS: gc_save_file_name TYPE string VALUE '01_HelloWorld.xlsx'.
INCLUDE zdemo_excel_outputopt_incl.

START-OF-SELECTION.
  " Creates active sheet
  CREATE OBJECT lo_excel.

  lo_style_color = lo_excel->add_new_style( ).
  lo_style_color->fill->filltype = zcl_excel_style_fill=>c_fill_solid.
  lo_style_color->fill->fgcolor-rgb  =
    zcl_excel_style_color=>create_new_argb( ip_red = 'C4' ip_green = 'D7' ip_blu = '9B' ).
  lv_style_color_guid = lo_style_color->get_guid( ).

  " Get active sheet
  lo_worksheet = lo_excel->get_active_worksheet( ).
  lo_worksheet->set_cell( ip_column = 'B' ip_row = 2 ip_value = 'Hello world' ip_style = lv_style_color_guid ).

  " Check Style
  PERFORM check_style.

  lo_worksheet->change_cell_style( ip_column = 'B' ip_row = 2 ip_alignment_horizontal = zcl_excel_style_alignment=>c_horizontal_center ).

  " Check Style
  PERFORM check_style.

  column_dimension = lo_worksheet->get_column_dimension( ip_column = 'B' ).
  column_dimension->set_width( ip_width = 21 ).

**\* Create output
  lcl_output=>output( lo_excel ).

FORM check_style.
  DATA lv_value TYPE zexcel_cell_value.
  DATA lv_rc  TYPE sysubrc.
  DATA lo_style TYPE REF TO zcl_excel_style.
  DATA lv_guid  TYPE zexcel_cell_style.
  DATA lv_rc_char TYPE char5.
  DATA lv_guid_char TYPE char32.

  TYPES:
  BEGIN OF ts_info,
    line TYPE char70,
  END OF ts_info,
  tt_info TYPE STANDARD TABLE OF ts_info.

  DATA lt_info TYPE tt_info.
  DATA ls_info TYPE ts_info.

  " Check Style
  lo_worksheet->get_cell(
    EXPORTING
      ip_column = 'B'
      ip_row    = 2
    IMPORTING
      ep_value = lv_value
      ep_rc = lv_rc
      ep_style  = lo_style
      ep_guid = lv_guid
  ).

  IF lo_style IS NOT BOUND.
    ls_info-line = 'B2 HAS NO STYLE'.
  ELSE.
    ls_info-line = 'B2 HAS STYLE'.
  ENDIF.
  APPEND ls_info TO lt_info.

  CONCATENATE 'VALUE:' lv_value INTO ls_info-line.
  APPEND ls_info TO lt_info.

  lv_rc_char = lv_rc.
  CONCATENATE 'RC:' lv_rc_char INTO ls_info-line.
  APPEND ls_info TO lt_info.

  lv_guid_char = lv_guid.
  CONCATENATE 'GUID:' lv_guid_char INTO ls_info-line.
  APPEND ls_info TO lt_info.

  CALL FUNCTION 'POPUP_WITH_TABLE_DISPLAY'
    EXPORTING
      endpos_col   = 85
      endpos_row   = 15
      startpos_col = 5
      startpos_row = 5
      titletext    = 'VALUES'
    TABLES
      valuetab     = lt_info
    EXCEPTIONS
      break_off    = 0
      OTHERS       = 0.
ENDFORM.                    "check_style

**Comment by StefanSchmoecker** [comment]
It's not a bug - it's a feature - or something like this.

When using the change_cell_style( ) method you switch the style from a dynamic style to a static style.  
The difference is:  All cells which have a dynamic style attached will change whenever the dynamic style changes.  The final output is only fixed when using the writer to output the data.
All cells with static cell styles won't be affected by any changes to other cells which have the same cellstyle at the moment but when they are changed the aquire a new cellstyle.  This is more like the behaviour when working with excel in on your frontend.

The final explanation:  The ep_style of the get_cell method returns the dynamic style - but since you changed to a static style you only get an empty style.

Workaround:  None at the moment.  We had no need for a "get static style"-method yet to return information about a cells style.
