### ISSUE TITLE
excel with macro causes dump

### ISSUE THREAD

**Issue by Wei-Ming** [abap2xlsx/abap2xlsx#313]
Hey,

i am playing around with this great tool to create own excel files. I tried to upload a excel file with a simple macro with report ZDEMO_EXCEL29. Every time when upload it, it causes a dump. I don't understand why?
We have installed version 7.0 of abap2xlsx. I used the file which was posted in the wiki (TestMacro.xlsm). When i debug the code, it always dump at ZCL_EXCEL_READER_2007=========CP, when it is trying to find directory (xl/drawings/_rels/drawing1.xml.rels) in zip which does not exist. What can i do? I already installed the addon 2 times with same results. Any other idea? What else could be wrong? 

thx, M.

**Comment by ivanfemia** [comment]
I think it is a bug.
Can you please provide us a copy of your excel as a test case.

**Comment by Wei-Ming** [comment]
Hi Ivan,

here the excel.

Von: Ivan [mailto:notifications@github.com] 
Gesendet: Donnerstag, 3. April 2014 18:07
An: ivanfemia/abap2xlsx
Cc: Wei-Ming
Betreff: Re: [abap2xlsx] excel with macro causes dump (#313)

I think it is a bug.
Can you please provide us a copy of your excel as a test case.

—
Reply to this email directly or view it on GitHub https://github.com/ivanfemia/abap2xlsx/issues/313#issuecomment-39470316 .  https://github.com/notifications/beacon/7136346__eyJzY29wZSI6Ik5ld3NpZXM6QmVhY29uIiwiZXhwaXJlcyI6MTcxMjE2MDQzMSwiZGF0YSI6eyJpZCI6MjkyMDAxODV9fQ==--afce3b5089cef00d62b065d967c05a566ca6b7c5.gif 

---

Diese E-Mail ist frei von Viren und Malware, denn der avast! Antivirus Schutz ist aktiv.
http://www.avast.com

**Comment by Wei-Ming** [comment]
can't send the file. just tried the same with the file from here:
https://github.com/ivanfemia/abap2xlsx/tree/master/resources
same result... :-(

**Comment by rplantiko** [comment]
Hello Wei-Ming (aka Butch :-) ),

since I have access to your SAP system, I tried to reproduce your problem. With ZDEMO_EXCEL29 and the test file from 

https://github.com/ivanfemia/abap2xlsx/blob/master/resources/TestMacro.xlsm

I could indeed reproduce your short dump! 

But this was a download error.  Using the above URL, you are downloading not the file but the HTML code which presents it in github! 

You have to go the detail view of the file, and download it from the button "Raw" using "Save link under". This way, you will copy the ressource from the right place which is: 

https://github.com/ivanfemia/abap2xlsx/raw/master/resources/TestMacro.xlsm

With this file, the report ZDEMO_EXCEL29 seemed to work with no problems, i.e. the roundtrip "read -> save" with abap2xlsx worked properly.

With the file that you can't send: Try to inspect it using zip (for example by changing the ending from .xlsm to .zip, and then open with double-click): xlsx and xlsm are actually zip files, therefore it should be possible to open thim with zip. 

If you are able to open your file with zip: Does it have the expected directory structure? 

Regards,
Rüdiger

**Comment by Wei-Ming** [comment]
Hi Rüdiger,

thank you for your reply.I went to the detail view of the file and open the context menu to save the from raw. But i still get the same error like before. I also tried the link which you provided and downloaded the file a couple of time. Same ressult.... what i am doing wrong?

regards, M.

**Comment by rplantiko** [comment]
Hello Butch, 

now I can reproduce the error by running report ZDEMO_EXCEL29 with the excel sheet 

https://github.com/ivanfemia/abap2xlsx/raw/master/resources/TestMacro.xlsm

The dump occurs in method LOAD_WORKSHEET_DRAWING of class ZCL_EXCEL_READER_2007, when it tries to read a file with path 

xl/drawings/_rels/drawing1.xml.rels

from the zip archive. There is no such file. Actually, the method is called with a correct path (IP_PATH) to an existing file:

xl/drawings/drawing1.xml

But then, in line 50 of method LOAD_WORKSHEET_DRAWING, with the statement 

  CONCATENATE dirname '_rels/' stripped_name '.rels'
    INTO rels_drawing_path.

the non-existing path is produced. When GET_IXML_FROM_ZIP_ARCHIVE is called with this invalid path, it raises an uncalled exception. 

For me, this looks similar to bug 253 (which is still open)

https://github.com/ivanfemia/abap2xlsx/issues/253

I don't know whether the relationship file exists at all in this case. If it is supposed to exist in some times, and in others not, then a TRY ... CATCH would be appropriate. If it is never supposed to exist, then the code which reads this relationship file should be skipped completely.

Regards,
Rüdiger

**Comment by StefanSchmoecker** [comment]
Tried to read the file with the demoreport 37 which now allows to read .xlsm files as well.
No exception being risen any more.  
Please check and close if solution satisfactory

**Comment by StefanSchmoecker** [comment]
No one has spoken that this is still a problem.  
I'll close this issue in 2 weeks if no one objects.

**Comment by StefanSchmoecker** [comment]
No follow up in the last 4 weeks - closed!
