### ISSUE TITLE
INSTALLING: Could not create WB object from OCN (type),  (name), ZCL_EXCEL (encl.)

### ISSUE THREAD

**Issue by ghost** [abap2xlsx/abap2xlsx#335]
Hello everyone,

I activated the class ZCL_EXCEL in transaction SE80 but the object still exist in the list of inactive objects in transaction SE80. When I doubleclick on the empty subitem of this object entry
 I get the message "Could not create WB object from OCN (type),  (name), ZCL_EXCEL (encl.)". (see attached image)
I installed the nugget file in a temporare package $TMP.
![problem_massage_zcl_excel](https://cloud.githubusercontent.com/assets/9315125/4697443/3fc65676-5826-11e4-94a9-0dc3fc7b77a1.jpg)
Can anybody tell me what the problem could be and how to solve this problem?

SAP System with EHP7:
SAP_BASIS 740 SP6

Best regards,
Markus

**Comment by mfallen** [comment]
I have the same problem here and ignored it ;-)

**Comment by ghost** [comment]
So you still have this entry in your list of inactive objects? Or is there a method to get this entry out of this list? 

And what is the problem??? I don´t understand this message!

**Comment by mfallen** [comment]
Yes, the entry remains as inactive object.
At the moment the only way to delete this - is hardly from database table? Maybe, I don't know....

**Comment by ivanfemia** [comment]
Have you tried to rebuild object list?
It seems really strange...

**Comment by ghost** [comment]
How can I rebuild the object list?

**Comment by ivanfemia** [comment]
From SE80
Select the package and right click. In other functionalities or in the top menu there should be a "Rebuild object list" option.

**Comment by ghost** [comment]
There is no change when I do the function "Rebuild object list".
The problem still exist.

**Comment by mfallen** [comment]
Correct, rebuild doesn't fix the issue.
Tried to debug, search in tables for more than one hour, found no solution --> ignore ;-)

**Comment by appyface** [comment]
I don't know what the root cause is, just that this always fixes it for me. I hope this works for you. To fix, add any text element, save and activate the class, the error is removed.

**Comment by appyface** [comment]
I found a much better solution not long after posting the above, but kept forgetting to come and post it.  I know it is an old post, but for those of us still using SAPLINK... 

When activating imported object for first time, a list of objects to activate will usally pop-up.  Click "whole worklist" button at bottom.  

REPT text objects will come into list, select all of these too for your objects and activate.

NOTE: Sometimes "whole worklist" doesn't appear because of way object is being activated (right click menu in SE80, or toolbar icon).  Activating main object on main screen of SE24, SE37, SE38 will usually bring the pop-up and also the "whole worklist" option.
