### ISSUE TITLE
Missing set overlap  for zcl_excel_graph_bars 

### ISSUE THREAD

**Issue by napalmek** [abap2xlsx/abap2xlsx#372]
![issue](https://cloud.githubusercontent.com/assets/3425962/7514400/3e8f8a32-f4bd-11e4-94ab-7e3ac0b15a23.png)

I can not set overloop for chart. Setting this parameter missing in alv2xlsx. If I am wrong, I apologize, but I do not know how to set this property.

Thanx for any answer.

**Comment by StefanSchmoecker** [comment]
Hello Napalmek,

I know that this bar-type is not fully supported because I encountered the problem a few weeks ago. 
You'll have to modify ZCL_EXCEL_WRITER_2007->CREATE_XL_CHARTS slightly to add support to this as well. It's only a minor change but I didn't have time to test my changes on my reference system yet.

**Comment by ivanfemia** [comment]
Hi Napalmek,

you can create a fork and improve the ZCL_EXCEL_WRITER_2007->CREATE_XL_CHARTS and propose a pull into the main repository.
Your contribution will be highly appreciated!

Ivan

**Comment by StefanSchmoecker** [comment]
Added feature.
Until this gets into the daily build get the latest version of the following classes/reports
Class ZCL_EXCEL_GRAPH_BARS  ( only to get the new constants defined there )
Class ZCL_EXCEL_WRITER_2007  ( to create stacked bars )
Report ZDEMO_EXCEL39  ( Demoreport for charts - added demo for stacked charts on 2nd sheet )
