### ISSUE TITLE
Template Reader 2007 - Paper Size not read

### ISSUE THREAD

**Issue by StefanSchmoecker** [abap2xlsx/abap2xlsx#396]
Missing feature:  Readerclass does not read PaperSize ( A4,A5, Letter legal ) etc.

**Comment by Jitsuryoku** [comment]
My company is pretty strict about editing code that is not developed internally, so I can't test this properly, without wasting a day or to set everything up in sandbox, but it seems to me that this needs 2 lines of code added (new lines marked with '>' before the line) at the current state: 

- One to add corresponding field to structure that holds parsed data 
- One to put that data into the object. I suppose more if there's a need to handle absence of that data, if such scenario is possible.

Around line 66 of ZCL_EXCEL_READER_2007->LOAD_WORKSHEET( )
```
  TYPES:  BEGIN OF lty_page_setup,
            id          TYPE string,
            orientation TYPE string,
            scale       TYPE string,
            fittoheight TYPE string,
            fittowidth  TYPE string,
>           papersize   TYPE string, "new line
          END OF lty_page_setup
```
Then at 616 (where the block for **pageSetup** parsing is)
```
  " Read in page setup "Read in page setup" 
  lo_ixml_pagesetup_elem = lo_ixml_worksheet->find_from_name( 'pageSetup' ).
  IF lo_ixml_pagesetup_elem IS NOT INITIAL.
    fill_struct_from_attributes( EXPORTING
                                   ip_element = lo_ixml_pagesetup_elem
                                 CHANGING
                                   cp_structure = ls_pagesetup ).
    io_worksheet->sheet_setup->orientation = ls_pagesetup-orientation.
    io_worksheet->sheet_setup->scale = ls_pagesetup-scale.
>   io_worksheet->sheet_setup->paper_size = ls_pagesetup-papersize. "new line
   .....
  ENDIF.
```

**Comment by gregorwolf** [comment]
Hi @Jitsuryoku I've added your code and merged it. I would suggest you get your own ABAP Developer Edition, install it using [sap-nw-abap-vagrant](https://github.com/sbcgua/sap-nw-abap-vagrant), Install abapGit, Install abap2xlsx and start contributing. Or maybe donate to a charity of your choice for this quick community support.

**Comment by Jitsuryoku** [comment]
Apologies for the secondary commit. I tested the code in a local class and only realized you've already updated it after creating the pull request. I also included paperWidth / paperHeight, but they appear to be rather useless in new versions of MS office.

**Comment by sandraros** [comment]
According to ECMA Office Open XML 2016, all 3 can be used, moreover the writer class already manages paper height and width, so I guess we should merge your latest proposal that I integrated in #984 (currently a draft PR, we'll check it soon).

NB: for those people who want to set a paper size in attribute worksheet->sheet_setup->paper_size, the constants for possible values are defined in the class `zcl_excel_sheet_setup` and are prefixed `c_papersize`.

**Comment by sandraros** [comment]
Steps to reproduce
- Create and execute the below program to generate the file `issue_396.xlsx`:
  ```abap
  REPORT.
  DATA: lo_excel     TYPE REF TO zcl_excel,
        lo_worksheet TYPE REF TO zcl_excel_worksheet.
  CONSTANTS: gc_save_file_name TYPE string VALUE 'issue_396.xlsx'.
  INCLUDE zdemo_excel_outputopt_incl.
  START-OF-SELECTION.
  CREATE OBJECT lo_excel.
    lo_worksheet = lo_excel->get_active_worksheet( ).
    lo_worksheet->set_cell( ip_columnrow = 'A1' ip_value = 'Paper height = 194.5mm and width = 141.8mm' ).
    lo_worksheet->sheet_setup->paper_height = '194.5mm'.
    lo_worksheet->sheet_setup->paper_width = '141.8mm'.
    lcl_output=>output( lo_excel ).
  ```
- Run the program `zdemo_excel37` to read `issue_396.xlsx`, it will write `37- Read template and output.xlsx` with the same `Sheet1.xml` containing `PageHeight` and `PageWidth`, which demonstrates that the fix "works" BUT see below.

BUT:
- when Excel 365 opens the file [issue_396.xlsx](https://github.com/abap2xlsx/abap2xlsx/files/8008767/issue_396.xlsx), it ignores `PageHeight` and `PageWidth`.
- the workaround would be to define the height and width via Excel 365 (example: [papersize_1900_1400.xlsx](https://github.com/abap2xlsx/abap2xlsx/files/8008764/papersize_1900_1400.xlsx)) then read via abap2xlsx the file as a template. Unfortunately Excel 365 creates an Excel file with `Sheet1.xml` which doesn't contain `PageHeight` and `PageWidth`. I think Excel stores data in `xl/printerSettings/printerSettings1.bin`.
- consequently, with abap2xlsx, there's currently no way to use a paper with custom height and width.
- further investigations:
  1. maybe Open Office works better?
  2. try to do a fix in abap2xlsx so that reading a template with the file `xl/printerSettings/printerSettings1.bin` and writing to a new Excel file would copy the printer settings unchanged.

@AndreaBorgia-Abo 
Should we abandon the fix #984 or keep it?
Should we create a separate issue to support reading and writing `xl/printerSettings/printerSettings1.bin`?

**Comment by AndreaBorgia-Abo** [comment]
I've been promised an upgrade to my Office 2013 license once my company laptop comes back from repairs, we'll see which version I get.
This is no review (too short on time now) but I'd say we keep this fix since it should work in all but the very newest Excel and then open a new issue as you suggested. I'll have a look at LibreOffice on Linux, if anything out of curiosity because proper support for that would be cool.

**Comment by AndreaBorgia-Abo** [comment]
**Libreoffice 7.3.1.1 on Debian/testing**
This is with the file produced by the program above:
![libreoffice](https://user-images.githubusercontent.com/25269970/154797111-a2874dec-a7c3-4f02-8713-6f53393541cd.png)

Feeding that file through zdemo_excel37 without the fix, we get a file looking like this:
![libreoffice2](https://user-images.githubusercontent.com/25269970/154797257-12f6970a-981e-4322-a057-687c4259e478.png)

With the fix in place:
![libreoffice3](https://user-images.githubusercontent.com/25269970/154798387-51e46d30-dbc7-43a4-a026-f31102f89454.png)


**Excel 2019 on Windows 11**
we have first:
![excel2019-outputfrom396-nofilter](https://user-images.githubusercontent.com/25269970/154797692-7fae37f7-8231-4030-a26c-53fd7e9f631e.png)

After going through zdemo_excel37:
![excel2019-outputfrom396-filtered](https://user-images.githubusercontent.com/25269970/154797795-b3e58ecb-7660-45c6-999d-14fe8ea1e324.png)


With fix in place, the page setting is still ignored but the again it wasn't there to begin with:
![excel2019-outputfrom396-filter-afterfix](https://user-images.githubusercontent.com/25269970/154798212-b0366d39-d560-4cce-ad9a-be35d77c86c5.png)


**Excel 2013 on Windows 10**
Now this is weird, it seems to behave like 2019, meaning that even the first (unfiltered) file still doesn't understand the papersize:
![ZA7xgQRRkn](https://user-images.githubusercontent.com/25269970/154798773-2cabdfa6-93f1-47df-9164-3fc1ccdadac0.png)



Back to your question about keeping this fix: before the last test with 2013 I was going to say "hell, yeah", now it's more of a "definite maybe", basically only Libreoffice cares about it :)
Do we need extra documentation? Should I try to pull some strings to get it?

**Comment by sandraros** [comment]
Thanks for the check! So, I guess we could merge the code, although it will work only for LibreOffice. Moving the PR status to "ready for review". I don't think it's worth adding more to this discussion, it's sufficient. Maybe in the future, someone can find a solution to force a page size in Excel.
