### ISSUE TITLE
abap2xlsx - Workbook protect

### ISSUE THREAD

**Issue by horcruxes77** [abap2xlsx/abap2xlsx#444]
hi,

is it still not possible to have the workbook protect?
I've read in SCN that its not possible, and also tried to edit ZDEMO_EXCEL18 but still no luck.

Thank you.

**Comment by ivanfemia** [comment]
If you want to block the access to the excel with a password, it is not possible, because it is not a OOXML standard but a functionality implemented by Microsoft (binary).
If you want to lock (with or without password) the workbook and/or the worksheet by changes you can using the proper methods.

Ivan
