### ISSUE TITLE
Move ABAP2XLSX from $TMP to Z Package

### ISSUE THREAD

**Issue by GH-RNA** [abap2xlsx/abap2xlsx#480]
Hi, guys.

When I've moved ABAP2XLS's objects from $TMP to Z package, it was created a request with 2 tasks:
- a workbench task, with all ABAP2XLS's objects   
- a repair task with a object: "Concept (Online Text Repository) - Short Texts"  LIMU SOTT ZPACKAGE , is this correct? 

Should I delete this repair task? What to do?

Thanks

**Comment by rmcknight001** [comment]
no it should be a workbench dev.correction task  not repair

On May 11, 2017 02:09, "GH-RNA" <notifications@github.com> wrote:

Hi, guys.

When I've moved ABAP2XLS's objects from $TMP to Z package, it was created a
repair request with a object: "Concept (Online Text Repository) - Short
Texts" LIMU SOTT ZPACKAGE , is this correct?

Thanks

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/ivanfemia/abap2xlsx/issues/480>, or mute the thread
