### ISSUE TITLE
Large XLSX file creation results into ABAP dump at IF_IXML_DOCUMENT~CREATE_SIMPLE_ELEMENT

### ISSUE THREAD

**Issue by janineparial** [abap2xlsx/abap2xlsx#643]
I have a report that is using ABAP2XLSX to generate XLSX file as the final output and writing it to the application server. The data is quite large, around 200K records. When I execute the report, whether in foreground or background, it ends up as an ABAP dump with message SYSTEM_NO_ROLL or MEM_ALLOC_FAILED. it gets stuck at IF_IXML_DOCUMENT~CREATE_SIMPLE_ELEMENT. Please help how to resolve :(

**Comment by Mind-Open** [comment]
Hi janineparial

Which class did you use to download datas ? 
In case of huge file, i will recomand you to use this class :
Zcl_excel_writer_huge_file.

I can extract several hundreds of thousands of lines spread over several tabs of an excel file.

**Comment by janineparial** [comment]
I am using ZCL_EXCEL_WRITER_2007 and ZIF_EXCEL_WRITER. should I use class Zcl_excel_writer_huge_file instead?

**Comment by bhavesh4321** [comment]
Any performance issue with Zcl_excel_writer_huge_file ?

**Comment by sandraros** [comment]
`ZCL_EXCEL_WRITER_HUGE_FILE` is using Simple Transformations instead of iXML, so I guess it should work better, but it doesn't handle all the Excel features that `ZCL_EXCEL_WRITER_2007` does.

I think we can consider this issue is a question, if it's answered can we close it?

In case you're missing some features with `ZCL_EXCEL_WRITER_HUGE_FILE`, please open an issue.

**Comment by sandraros** [comment]
No answer. Closing.
