### ISSUE TITLE
`SET_CELL_FORMULA` doesn't work for cells not previously initialized

### ISSUE THREAD

**Issue by sandraros** [abap2xlsx/abap2xlsx#866]
The following code doesn't show a formula in cell A1:
```
REPORT.
CONSTANTS: gc_save_file_name TYPE string VALUE 'test.xlsx'.
INCLUDE zdemo_excel_outputopt_incl.
START-OF-SELECTION.
  DATA(lo_excel) = new zcl_excel( ).
  DATA(lo_worksheet) = lo_excel->get_active_worksheet( ).
  lo_worksheet->set_cell_formula( ip_column = 1 ip_row = 1 ip_formula = '"hello"&" "&"world"' ).
  lcl_output=>output( lo_excel ).
```
Actual result:
![image](https://user-images.githubusercontent.com/34005250/139944168-c786d786-fd54-4b6d-9b21-df3597d6674f.png)

Expected result:
![image](https://user-images.githubusercontent.com/34005250/139944263-968f4215-847a-47b0-a782-856e14dd22ca.png)

**Comment by AndreaBorgia-Abo** [comment]
@sandraros I'm reviewing the SET_AREA PR and one thing caught my eye in your [test report](https://github.com/sapmentors/abap2xlsx/issues/867#issue-1041627058) and it's that the workaround for this bug is apparently still needed but ONLY when running against Libreoffice 7.2.2.2 under Linux.

With workaround:
![immagine](https://user-images.githubusercontent.com/25269970/141492562-3c4f263e-b0ec-4f8c-bcc4-07263c1421bb.png)


Without workaround:
![immagine](https://user-images.githubusercontent.com/25269970/141492447-b4a35b9a-f5e0-46ad-b414-0d4660408847.png)

Excel 2013 behaves as advertised, so I am NOT reopening this.
