### ISSUE TITLE
refactoring: use of cl_object_collection_iterator

### ISSUE THREAD

**Issue by larshp** [abap2xlsx/abap2xlsx#880]
object `cl_object_collection_iterator` is not a steampunk relasesed object #632

suggest implementing the iterator functionality in a new `zcl_excel_iterator` class, and using that instead

**Comment by larshp** [comment]
and `cl_object_collection`

**Comment by sandraros** [comment]
Merged → Closing.

**Comment by larshp** [comment]
only first part done, todo: use the new classes

**Comment by sandraros** [comment]
For information, I realize now that it breaks the ascendant compatibility, my code based on abap2xlsx doesn't compile anymore, I need to replace `cl_object_collection_iterator` everywhere. Not a big deal but we'd better have released a new major version i.e. contains incompatible changes, so that the client is aware to review all code that is using abap2xlsx.

**Comment by gregorwolf** [comment]
@sandraros what's the exact NetWeaver ABAP version where you ran into issues?

**Comment by sandraros** [comment]
For instance, my custom program using abap2xlsx was:
```abap
DATA: workbook       TYPE REF TO zcl_excel,
      style_iterator TYPE REF TO cl_object_collection_iterator.
...
style_iterator = workbook->get_styles_iterator( ). "<======= syntax error
```
to be changed into:
```abap
DATA: workbook       TYPE REF TO zcl_excel,
      style_iterator TYPE REF TO zcl_excel_collection_iterator. "<======= fix
...
style_iterator = workbook->get_styles_iterator( ).
```
