### ISSUE TITLE
Problem with SharedString parsing. 

### ISSUE THREAD

**Issue by DerBrutus** [abap2xlsx/abap2xlsx#895]
Hello everyone,

i use the class zcl_excel_reader_huge_file.

I have a strange problem with an excel file.
I think it is due to strange entries in the sharedStrings.xml.
The following text is in a cell:
![image](https://user-images.githubusercontent.com/94889843/142989263-7eedb45c-4a46-4061-827f-7cbc14df7ee8.png)

In the sharedStrings.xml is following:

![image](https://user-images.githubusercontent.com/94889843/142990411-f057b583-0078-4d52-9888-413b6162b358.png)

As a result, there are two rows in the internal table for the cell text "Material Number"
("M", "aterial number"). Now the key of the rows in the internal table are wrong. 

Can anyone help?

Many greetings

Brutus

p.s. I use the Class

**Comment by sandraros** [comment]
Hello. I think it's a duplicate of issue #614. I will propose the fix very soon. In that issue, [EMertens](https://github.com/EMertens) proposed a fix already which worked for him and for me, so you may check if that suits you already.
NB: if possible, please attach your Excel file and the code to reproduce so that we can check your issue. (I guess that running `ZDEMO_EXCEL37` with option `zcl_excel_reader_huge_file` is sufficient)

**Comment by DerBrutus** [comment]
I will check the Issue, thank you. 

Here is the testfile. 
[testFile.xlsx](https://github.com/sapmentors/abap2xlsx/files/7600890/testFile.xlsx)

P.S.
With the class zcl_excel reader 2007 it works fine.

**Comment by sandraros** [comment]
Hi, this was just fixed through #897. Could you please check if it solves your issue? If yes, please close it. Thank you.

**Comment by AndreaBorgia-Abo** [comment]
This is the testfile above with Excel:
![immagine](https://user-images.githubusercontent.com/25269970/143879016-b5523667-f073-46a4-9eb6-a4345585642d.png)

and with my test program:
![immagine](https://user-images.githubusercontent.com/25269970/143879167-84ac1bb5-daee-41a7-b6e9-422c86d8b063.png)

It should indeed be ok, right, @DerBrutus ?
